---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Mindful/Mindful.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/2191/articles/214576/master/file/figures/Mindful/Mindful.png"
    folder_url: "/users/2191/articles/214576/master/folder/figures/Mindful"
